//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/UserInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInput"",
    ""maps"": [
        {
            ""name"": ""Machines"",
            ""id"": ""f138d6d8-3613-4d38-a3ed-0768c2af83aa"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a9c9e28d-4a52-48fa-a88b-e058ef45a0b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""441e9e87-6fd4-4561-80e3-0cb7438b9ea9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""adbe4bf7-1857-403f-bc9e-9cfceaa9dfd2"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""mobile"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73adfcd3-d2c8-4ab4-91be-33ea30b38ca4"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""3d94f16f-c89f-4b46-91e3-fc69238bff52"",
            ""actions"": [
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""8eb30563-45ad-4c37-be7a-9f2efae22a23"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchIsPressed"",
                    ""type"": ""Value"",
                    ""id"": ""ba265548-5d81-4561-bf19-d794db375acd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondTouchIsPressed"",
                    ""type"": ""Value"",
                    ""id"": ""276308b6-2ed9-4f0d-a1e4-187757ee79d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondTouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""ab00f380-e65b-4b2b-b1c0-7c71facf63f8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1a36a09e-2622-45ae-949d-35c6c9ac9bea"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba549ee7-c90f-448f-80fa-dea748d5225f"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchIsPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""238b742a-b6ce-491f-880b-b442d32e5c4a"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondTouchIsPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8702eac8-4b7d-4f3b-b8dc-794e82136177"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondTouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""computer"",
            ""bindingGroup"": ""computer"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""mobile"",
            ""bindingGroup"": ""mobile"",
            ""devices"": []
        },
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": []
        }
    ]
}");
        // Machines
        m_Machines = asset.FindActionMap("Machines", throwIfNotFound: true);
        m_Machines_Select = m_Machines.FindAction("Select", throwIfNotFound: true);
        m_Machines_Position = m_Machines.FindAction("Position", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_TouchPosition = m_Player.FindAction("TouchPosition", throwIfNotFound: true);
        m_Player_TouchIsPressed = m_Player.FindAction("TouchIsPressed", throwIfNotFound: true);
        m_Player_SecondTouchIsPressed = m_Player.FindAction("SecondTouchIsPressed", throwIfNotFound: true);
        m_Player_SecondTouchPosition = m_Player.FindAction("SecondTouchPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Machines
    private readonly InputActionMap m_Machines;
    private IMachinesActions m_MachinesActionsCallbackInterface;
    private readonly InputAction m_Machines_Select;
    private readonly InputAction m_Machines_Position;
    public struct MachinesActions
    {
        private @UserInput m_Wrapper;
        public MachinesActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Machines_Select;
        public InputAction @Position => m_Wrapper.m_Machines_Position;
        public InputActionMap Get() { return m_Wrapper.m_Machines; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MachinesActions set) { return set.Get(); }
        public void SetCallbacks(IMachinesActions instance)
        {
            if (m_Wrapper.m_MachinesActionsCallbackInterface != null)
            {
                @Select.started -= m_Wrapper.m_MachinesActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_MachinesActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_MachinesActionsCallbackInterface.OnSelect;
                @Position.started -= m_Wrapper.m_MachinesActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_MachinesActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_MachinesActionsCallbackInterface.OnPosition;
            }
            m_Wrapper.m_MachinesActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
            }
        }
    }
    public MachinesActions @Machines => new MachinesActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_TouchPosition;
    private readonly InputAction m_Player_TouchIsPressed;
    private readonly InputAction m_Player_SecondTouchIsPressed;
    private readonly InputAction m_Player_SecondTouchPosition;
    public struct PlayerActions
    {
        private @UserInput m_Wrapper;
        public PlayerActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchPosition => m_Wrapper.m_Player_TouchPosition;
        public InputAction @TouchIsPressed => m_Wrapper.m_Player_TouchIsPressed;
        public InputAction @SecondTouchIsPressed => m_Wrapper.m_Player_SecondTouchIsPressed;
        public InputAction @SecondTouchPosition => m_Wrapper.m_Player_SecondTouchPosition;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @TouchPosition.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTouchPosition;
                @TouchPosition.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTouchPosition;
                @TouchIsPressed.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTouchIsPressed;
                @TouchIsPressed.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTouchIsPressed;
                @TouchIsPressed.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTouchIsPressed;
                @SecondTouchIsPressed.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondTouchIsPressed;
                @SecondTouchIsPressed.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondTouchIsPressed;
                @SecondTouchIsPressed.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondTouchIsPressed;
                @SecondTouchPosition.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondTouchPosition;
                @SecondTouchPosition.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondTouchPosition;
                @SecondTouchPosition.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondTouchPosition;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TouchPosition.started += instance.OnTouchPosition;
                @TouchPosition.performed += instance.OnTouchPosition;
                @TouchPosition.canceled += instance.OnTouchPosition;
                @TouchIsPressed.started += instance.OnTouchIsPressed;
                @TouchIsPressed.performed += instance.OnTouchIsPressed;
                @TouchIsPressed.canceled += instance.OnTouchIsPressed;
                @SecondTouchIsPressed.started += instance.OnSecondTouchIsPressed;
                @SecondTouchIsPressed.performed += instance.OnSecondTouchIsPressed;
                @SecondTouchIsPressed.canceled += instance.OnSecondTouchIsPressed;
                @SecondTouchPosition.started += instance.OnSecondTouchPosition;
                @SecondTouchPosition.performed += instance.OnSecondTouchPosition;
                @SecondTouchPosition.canceled += instance.OnSecondTouchPosition;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_computerSchemeIndex = -1;
    public InputControlScheme computerScheme
    {
        get
        {
            if (m_computerSchemeIndex == -1) m_computerSchemeIndex = asset.FindControlSchemeIndex("computer");
            return asset.controlSchemes[m_computerSchemeIndex];
        }
    }
    private int m_mobileSchemeIndex = -1;
    public InputControlScheme mobileScheme
    {
        get
        {
            if (m_mobileSchemeIndex == -1) m_mobileSchemeIndex = asset.FindControlSchemeIndex("mobile");
            return asset.controlSchemes[m_mobileSchemeIndex];
        }
    }
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IMachinesActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnTouchPosition(InputAction.CallbackContext context);
        void OnTouchIsPressed(InputAction.CallbackContext context);
        void OnSecondTouchIsPressed(InputAction.CallbackContext context);
        void OnSecondTouchPosition(InputAction.CallbackContext context);
    }
}
